### PR TITLE
Update test guide to reflect v10 changes

### PR DESCRIPTION
**Pull request by danielsogl**

### CODE REVIEW

**Comment by jamuhl** [comment]
thank you

**Comment by Vanuan** [comment]
@danielsogl I followed the example in this PR. If fails with "`TypeError: Cannot read property 'type' of undefined`". The reason why it happens is that you didn't provide `initReactI18next` function in a module jest mock.

**Comment by Vanuan** [comment]
See also https://stackoverflow.com/questions/55507684/how-to-fix-typeerror-cannot-read-property-type-of-undefined-when-testing-i1

**Comment by Vanuan** [comment]
Also this issue is mentioned in #63

**Comment by jamuhl** [comment]
@Vanuan there is no need to use `initReactI18next` as long as the `t` function gets mocked -> it does not use the i18next instance at all using mocks for testing.

So this is "just" an issue for typescript users - I guess.

**Comment by Vanuan** [comment]
@jamuhl the error is thrown from `i18n
  .use`. Essentially, it's `i18n.use(undefined)`.

If there's no need to use `initReactI18next` why do you mock it in the example?

**Comment by ciruss** [comment]
I had the same problem with `initReactI18next` and `i18n.use(undefined)` I got it working like this
`jest.mock('react-i18next', () => {
  const useMock = [k => k, {}];
  useMock.t = k => k;

  return {
    useTranslation: () => useMock,
    initReactI18next: () => {}
  };
});`

I added this to my CRA setupTest.js file

**Pull request merged**
