### PR TITLE
1185 contribution ( updating step by step guide with translation file location information )

### PR DESCRIPTION
**Pull request by gnusiva**
adding translation file location

#### Checklist

- [ ] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by gnusiva** [comment]
Refer: https://github.com/i18next/react-i18next/issues/1185

**Comment by jamuhl** [comment]
This is not 100% correct...files are loaded from `/locales/<langulage_code>/translation.json` react-script just per default serves the file in the public folder as static files...

**Comment by gnusiva** [comment]
> This is not 100% correct...files are loaded from `/locales/<langulage_code>/translation.json` react-script just per default serves the file in the public folder as static files...

updated.

**Comment by jamuhl** [comment]
thank you

**Pull request merged**
